name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./dotnet-sample

      - name: Build
        run: dotnet build ./dotnet-sample --no-restore --configuration Release

      - name: Publish self-contained EXE
        run: |
          dotnet publish ./dotnet-sample \
            --configuration Release \
            --runtime win-x64 \
            --self-contained true \
            --output ./output
      # Common runtimes: win-x64, linux-x64, osx-x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: ./output
          
      - name: Run Tests (if any)
        run: echo "No tests yet!"
